name: Deploy Website
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**/*
      - .github/workflows/deploy-website.yml

defaults:
  run:
    working-directory: app/

jobs:
  terraform:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build -- --mode production

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://react-s3-static-website
